### ISSUE TITLE
[Angular Component] Modal doesn't run fade out animation when user clicks close button

### ISSUE THREAD

**Issue by glaucomorais** [vmware/clarity#1148]
[x ] bug
[ ] feature request
[ ] enhancement

### Expected behavior
Modal disappear with a fade out animation when user clicks close button using Angular components.

### Actual behavior
Suddenly disappear after user clicks close button.

### Reproduction of behavior
Is possible to see the behavior on the examples page of the documentation (Angular Components section):
https://vmware.github.io/clarity/documentation/modals#examples

### Environment details

* **Angular version:** 4.2.5

* **Clarity version:** 
clarity-angular: 0.10.0-alpha.3,
clarity-icons: 0.10.0-alpha.3,
clarity-ui: 0.10.0-alpha.3

* **OS and version:** Elementary OS 0.4.1 Loki (Ubuntu 16.04.2 LTS) 64bits

* **Browser:** Chrome 59.0.3071.115

**Comment by gnomeontherun** [comment]
Confirm this is a known issue and we've been tracking an Angular bug with animations that was recently fixed (hopefully), but requires us to use new animation features to address this. 

See https://github.com/angular/angular/issues/15798

**Comment by adityarb88** [comment]
@belyan provided a StackBlitz to replicate this issue: https://clarity-light-theme-v10-d5xkbh.stackblitz.io/

Linking it here.

**Comment by hippee-lee** [comment]
Link to stackblitz with editor: https://stackblitz.com/edit/clarity-light-theme-v10-d5xkbh

**Comment by belyan** [comment]
It looks like [Angular issue](https://github.com/angular/angular/issues/18305) has been fixed in version 5.0.0-rc.3. Could you please support this fix on your side?

**Comment by jeeyun** [comment]
I believe we haven't revisited this on our side since the fix. Putting on backlog to take a look again.

**Comment by mathisscott** [comment]
I've verified this is still an issue.

**Comment by gnomeontherun** [comment]
This issue persists, as the fix in Angular does not appear to have addressed the root cause. While this is a UX annoyance, it doesn't have a major impact on the user. We're actively working on this with Clarity Core animations, so that will be the future recommendation.

In an effort to clean up our backlog and focus our attention, I’m going to close this as likely to be resolved by upcoming implementations in Clarity Core. Please follow our development and releases to see when we release relevant components to make this possible.
